/**
 * This file is auto-generated by Supabase CLI.
 * Run: pnpm db:generate-types to regenerate after schema changes.
 *
 * Placeholder types until Supabase is set up locally.
 */

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]

export type Database = {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string
          email: string
          full_name: string | null
          avatar_url: string | null
          timezone: string
          locale: string
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          email: string
          full_name?: string | null
          avatar_url?: string | null
          timezone?: string
          locale?: string
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          email?: string
          full_name?: string | null
          avatar_url?: string | null
          timezone?: string
          locale?: string
          updated_at?: string
        }
      }
      todos: {
        Row: {
          id: string
          user_id: string
          title: string
          description: string | null
          status: 'todo' | 'in_progress' | 'done' | 'cancelled'
          priority: 'low' | 'medium' | 'high' | 'urgent'
          due_date: string | null
          completed_at: string | null
          tags: string[]
          sort_order: number
          created_at: string
          updated_at: string
          deleted_at: string | null
        }
        Insert: {
          id?: string
          user_id: string
          title: string
          description?: string | null
          status?: 'todo' | 'in_progress' | 'done' | 'cancelled'
          priority?: 'low' | 'medium' | 'high' | 'urgent'
          due_date?: string | null
          completed_at?: string | null
          tags?: string[]
          sort_order?: number
          created_at?: string
          updated_at?: string
          deleted_at?: string | null
        }
        Update: {
          title?: string
          description?: string | null
          status?: 'todo' | 'in_progress' | 'done' | 'cancelled'
          priority?: 'low' | 'medium' | 'high' | 'urgent'
          due_date?: string | null
          completed_at?: string | null
          tags?: string[]
          sort_order?: number
          updated_at?: string
          deleted_at?: string | null
        }
      }
      calendar_events: {
        Row: {
          id: string
          user_id: string
          title: string
          description: string | null
          location: string | null
          start_time: string
          end_time: string
          all_day: boolean
          color: string
          recurrence: Json | null
          external_id: string | null
          created_at: string
          updated_at: string
          deleted_at: string | null
        }
        Insert: {
          id?: string
          user_id: string
          title: string
          description?: string | null
          location?: string | null
          start_time: string
          end_time: string
          all_day?: boolean
          color?: string
          recurrence?: Json | null
          external_id?: string | null
          created_at?: string
          updated_at?: string
          deleted_at?: string | null
        }
        Update: {
          title?: string
          description?: string | null
          location?: string | null
          start_time?: string
          end_time?: string
          all_day?: boolean
          color?: string
          recurrence?: Json | null
          updated_at?: string
          deleted_at?: string | null
        }
      }
      reminders: {
        Row: {
          id: string
          user_id: string
          event_id: string | null
          todo_id: string | null
          remind_at: string
          channel: 'push' | 'in_app' | 'both'
          status: 'pending' | 'sent' | 'failed' | 'cancelled'
          message: string | null
          sent_at: string | null
          retry_count: number
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          event_id?: string | null
          todo_id?: string | null
          remind_at: string
          channel?: 'push' | 'in_app' | 'both'
          status?: 'pending' | 'sent' | 'failed' | 'cancelled'
          message?: string | null
          sent_at?: string | null
          retry_count?: number
          created_at?: string
        }
        Update: {
          remind_at?: string
          channel?: 'push' | 'in_app' | 'both'
          status?: 'pending' | 'sent' | 'failed' | 'cancelled'
          message?: string | null
          sent_at?: string | null
          retry_count?: number
        }
      }
      planner_entries: {
        Row: {
          id: string
          user_id: string
          plan_date: string
          title: string
          notes: string | null
          start_time: string
          end_time: string
          color: string
          todo_id: string | null
          event_id: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          plan_date: string
          title: string
          notes?: string | null
          start_time: string
          end_time: string
          color?: string
          todo_id?: string | null
          event_id?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          plan_date?: string
          title?: string
          notes?: string | null
          start_time?: string
          end_time?: string
          color?: string
          todo_id?: string | null
          event_id?: string | null
          updated_at?: string
        }
      }
      trips: {
        Row: {
          id: string
          user_id: string
          title: string
          description: string | null
          destination: string | null
          start_date: string
          end_date: string
          status: 'planning' | 'confirmed' | 'ongoing' | 'completed' | 'cancelled'
          cover_image: string | null
          budget: number | null
          currency: string
          tags: string[]
          created_at: string
          updated_at: string
          deleted_at: string | null
        }
        Insert: {
          id?: string
          user_id: string
          title: string
          description?: string | null
          destination?: string | null
          start_date: string
          end_date: string
          status?: 'planning' | 'confirmed' | 'ongoing' | 'completed' | 'cancelled'
          cover_image?: string | null
          budget?: number | null
          currency?: string
          tags?: string[]
          created_at?: string
          updated_at?: string
          deleted_at?: string | null
        }
        Update: {
          title?: string
          description?: string | null
          destination?: string | null
          start_date?: string
          end_date?: string
          status?: 'planning' | 'confirmed' | 'ongoing' | 'completed' | 'cancelled'
          cover_image?: string | null
          budget?: number | null
          currency?: string
          tags?: string[]
          updated_at?: string
          deleted_at?: string | null
        }
      }
      trip_members: {
        Row: {
          trip_id: string
          user_id: string
          role: string
          joined_at: string
        }
        Insert: {
          trip_id: string
          user_id: string
          role?: string
          joined_at?: string
        }
        Update: {
          role?: string
        }
      }
      itinerary_items: {
        Row: {
          id: string
          trip_id: string
          user_id: string
          day_number: number
          category: 'transport' | 'accommodation' | 'activity' | 'restaurant' | 'sightseeing' | 'other'
          title: string
          description: string | null
          location: string | null
          start_time: string | null
          end_time: string | null
          cost: number | null
          currency: string
          booking_ref: string | null
          url: string | null
          notes: string | null
          sort_order: number
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          trip_id: string
          user_id: string
          day_number: number
          category?: 'transport' | 'accommodation' | 'activity' | 'restaurant' | 'sightseeing' | 'other'
          title: string
          description?: string | null
          location?: string | null
          start_time?: string | null
          end_time?: string | null
          cost?: number | null
          currency?: string
          booking_ref?: string | null
          url?: string | null
          notes?: string | null
          sort_order?: number
          created_at?: string
          updated_at?: string
        }
        Update: {
          day_number?: number
          category?: 'transport' | 'accommodation' | 'activity' | 'restaurant' | 'sightseeing' | 'other'
          title?: string
          description?: string | null
          location?: string | null
          start_time?: string | null
          end_time?: string | null
          cost?: number | null
          currency?: string
          booking_ref?: string | null
          url?: string | null
          notes?: string | null
          sort_order?: number
          updated_at?: string
        }
      }
      expense_groups: {
        Row: {
          id: string
          name: string
          description: string | null
          created_by: string
          currency: string
          category: string
          trip_id: string | null
          image_url: string | null
          is_archived: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          name: string
          description?: string | null
          created_by: string
          currency?: string
          category?: string
          trip_id?: string | null
          image_url?: string | null
          is_archived?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          name?: string
          description?: string | null
          currency?: string
          category?: string
          trip_id?: string | null
          image_url?: string | null
          is_archived?: boolean
          updated_at?: string
        }
      }
      group_members: {
        Row: {
          group_id: string
          user_id: string
          role: string
          joined_at: string
        }
        Insert: {
          group_id: string
          user_id: string
          role?: string
          joined_at?: string
        }
        Update: {
          role?: string
        }
      }
      expenses: {
        Row: {
          id: string
          group_id: string
          paid_by: string
          title: string
          description: string | null
          amount: number
          currency: string
          category: string
          split_type: 'equal' | 'exact' | 'percentage' | 'shares'
          expense_date: string
          receipt_url: string | null
          created_at: string
          updated_at: string
          deleted_at: string | null
        }
        Insert: {
          id?: string
          group_id: string
          paid_by: string
          title: string
          description?: string | null
          amount: number
          currency?: string
          category?: string
          split_type?: 'equal' | 'exact' | 'percentage' | 'shares'
          expense_date?: string
          receipt_url?: string | null
          created_at?: string
          updated_at?: string
          deleted_at?: string | null
        }
        Update: {
          title?: string
          description?: string | null
          amount?: number
          currency?: string
          category?: string
          split_type?: 'equal' | 'exact' | 'percentage' | 'shares'
          expense_date?: string
          receipt_url?: string | null
          updated_at?: string
          deleted_at?: string | null
        }
      }
      expense_splits: {
        Row: {
          id: string
          expense_id: string
          user_id: string
          amount: number
          percentage: number | null
          shares: number | null
          is_settled: boolean
          settled_at: string | null
        }
        Insert: {
          id?: string
          expense_id: string
          user_id: string
          amount: number
          percentage?: number | null
          shares?: number | null
          is_settled?: boolean
          settled_at?: string | null
        }
        Update: {
          amount?: number
          percentage?: number | null
          shares?: number | null
          is_settled?: boolean
          settled_at?: string | null
        }
      }
      settlements: {
        Row: {
          id: string
          group_id: string
          paid_by: string
          paid_to: string
          amount: number
          currency: string
          notes: string | null
          settled_at: string
          created_at: string
        }
        Insert: {
          id?: string
          group_id: string
          paid_by: string
          paid_to: string
          amount: number
          currency?: string
          notes?: string | null
          settled_at?: string
          created_at?: string
        }
        Update: {
          notes?: string | null
        }
      }
      notification_queue: {
        Row: {
          id: string
          user_id: string
          type: string
          payload: Json
          status: 'queued' | 'processing' | 'sent' | 'failed'
          scheduled_at: string
          processed_at: string | null
          error: string | null
          retry_count: number
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          type: string
          payload?: Json
          status?: 'queued' | 'processing' | 'sent' | 'failed'
          scheduled_at?: string
          processed_at?: string | null
          error?: string | null
          retry_count?: number
          created_at?: string
        }
        Update: {
          status?: 'queued' | 'processing' | 'sent' | 'failed'
          processed_at?: string | null
          error?: string | null
          retry_count?: number
        }
      }
      push_subscriptions: {
        Row: {
          id: string
          user_id: string
          endpoint: string
          p256dh: string
          auth: string
          user_agent: string | null
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          endpoint: string
          p256dh: string
          auth: string
          user_agent?: string | null
          created_at?: string
        }
        Update: {
          p256dh?: string
          auth?: string
          user_agent?: string | null
        }
      }
    }
    Views: Record<string, never>
    Functions: Record<string, never>
    Enums: {
      todo_status: 'todo' | 'in_progress' | 'done' | 'cancelled'
      todo_priority: 'low' | 'medium' | 'high' | 'urgent'
      reminder_channel: 'push' | 'in_app' | 'both'
      reminder_status: 'pending' | 'sent' | 'failed' | 'cancelled'
      trip_status: 'planning' | 'confirmed' | 'ongoing' | 'completed' | 'cancelled'
      itinerary_category: 'transport' | 'accommodation' | 'activity' | 'restaurant' | 'sightseeing' | 'other'
      split_type: 'equal' | 'exact' | 'percentage' | 'shares'
      notification_type: string
      notification_status: 'queued' | 'processing' | 'sent' | 'failed'
    }
  }
}

export type Tables<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Row']
export type Enums<T extends keyof Database['public']['Enums']> = Database['public']['Enums'][T]
export type TablesInsert<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Insert']
export type TablesUpdate<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Update']
